version: "3.7"
services:
  chat-ui:
    image: harbor.linch.live/react/chat-ui:37ac2b7-20210510-0048
    container_name: chat-ui
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/timezone:/etc/localtime:ro
    ports: 
      - 3000:3000
    restart: always
    networks: 
      - nginx
networks:
  nginx:
    external: true
    name: nginx
