version: "3.7"
services:
  chat-ui:
    image:  react/chat-ui:latest
    container_name: chat-ui
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 3000:3000
    restart: always
    networks: 
      - nginx
networks:
  nginx:
    external: true
    name: nginx
